### ISSUE TITLE
[Error 290] Your current CPU is not supported. Ryzen 5 3600.

### ISSUE THREAD

**Issue by V3semir** [pierre-picard/minibot-wow#3]
Hello, I have a quick question. Is Ryzen 5 3600 CPU supported? I followed the GitHub guide and also did all the steps Titan's mentioned in his troubleshooting thread but I'm still getting "[Error 290] Your current CPU is not supported." I saw on the forum that someone's using the same CPU so it shouldn't throw this error I guess?

![1](https://user-images.githubusercontent.com/45462483/96880962-0eb35280-147e-11eb-9672-487040f8a8bb.png)

![2](https://user-images.githubusercontent.com/45462483/96880964-0f4be900-147e-11eb-9766-8ca2900e5839.png)

![3](https://user-images.githubusercontent.com/45462483/96880957-0e1abc00-147e-11eb-86e4-dcbfa68d45f9.png)

![4](https://user-images.githubusercontent.com/45462483/96882302-76b66880-147f-11eb-8fad-442f395d7c6d.png)

Edit:
After updating Windows to the 20H2 I'm getting a different error:

![5](https://user-images.githubusercontent.com/45462483/96935816-2c57da80-14c5-11eb-9f58-065f55a0cb11.png)

**Comment by pierre-picard** [comment]
20H2 is yet to be supported. It may still take 24-48 hours.
