### ISSUE TITLE
Running minibot on a VM

### ISSUE THREAD

**Issue by buloti** [pierre-picard/minibot-wow#6]
I can pass the virtualization test (activate virtualization on VM bios). I can start the launcher and enter option but when I click to start the wow session it freeze and log off the user. Do you know a way to make it work with VM? I am using Esxi from vmware.

**Comment by qianmianf** [comment]
你好有什么办法可以联系到你

**Comment by Moby232** [comment]
I have about the same problem, after starting my system constantly reboots
