### ISSUE TITLE
does then minibot support coroutine?

### ISSUE THREAD

**Issue by txt1899** [pierre-picard/minibot-wow#7]
does the minibot support coroutine?
I want to know this, because luabox does not support.

**Comment by pierre-picard** [comment]
Yes and why not?

We only unlock API and provide API extensions. You only get additional features on top of existing standard Lua, which should include coroutine.

**Comment by txt1899** [comment]
is there any way to contact you?

**Comment by pierre-picard** [comment]
I have not been on this project anymore for a while. But there are a few staff out there helping you further. They have a telegram: https://t.me/joinchat/WA_0pWEBKg8Sy1EB

Mostly the system is on OEM basis so you can also find good support from some OEM vendors.

**Comment by txt1899** [comment]
> I have not been on this project anymore for a while. But there are a few staff out there helping you further. They have a telegram: https://t.me/joinchat/WA_0pWEBKg8Sy1EB
> 
> Mostly the system is on OEM basis so you can also find good support from some OEM vendors.

a little troublesome, only tested some API, "RunScript" can be HOOK ...

**Comment by pierre-picard** [comment]
If you read the document carefully, you should focus on ```unique copy of "wmbapi" table``` passed into the independent project scripts. If you don't use our project system, such as a plain AddOn script, there is no way to prevent any API hooking.

**Comment by pierre-picard** [comment]
> > I have not been on this project anymore for a while. But there are a few staff out there helping you further. They have a telegram: https://t.me/joinchat/WA_0pWEBKg8Sy1EB
> > Mostly the system is on OEM basis so you can also find good support from some OEM vendors.
> 
> a little troublesome, only tested some API, "RunScript" can be HOOK ...

If you read the document carefully, you should focus on unique copy of "wmbapi" table passed into the independent project scripts. So whatever wmbapi table is changed outside will not affect it.

If you don't use our project system, such as a plain AddOn script, there is no way to prevent any API hooking.

**Comment by txt1899** [comment]
> > > I have not been on this project anymore for a while. But there are a few staff out there helping you further. They have a telegram: https://t.me/joinchat/WA_0pWEBKg8Sy1EB
> > > Mostly the system is on OEM basis so you can also find good support from some OEM vendors.
> > 
> > 
> > a little troublesome, only tested some API, "RunScript" can be HOOK ...
> 
> If you read the document carefully, you should focus on `unique copy of "wmbapi" table` passed into the independent project scripts. So whatever wmbapi table is changed outside will not affect it.
> 
> If you don't use our project system, such as a plain AddOn script, there is no way to prevent any API hooking.
> 
> For further questions, please join the channel for more discussions as I am not on duty to do any support.

thank you, I am reading the document carefully.
